### ISSUE TITLE
[Feature] Rename prefix in special collection

### ISSUE THREAD

**Issue by LLKoder** [Weisl/simple_renaming_panel#100]
I can't rename prefix in special collection / s.

What I do:

1. Select special collection / s.
2. Change Target to Collection.
3. Type new name in prefix.
4. Click Add Prefix.
5. My **all** collections in project is renamed.

However, when I rename special object / s all ok.

**Comment by LLKoder** [comment]
...The suffix has the same problem.

**Comment by LLKoder** [comment]
![image](https://user-images.githubusercontent.com/50442676/145703024-1d61c4ec-eafc-4fa8-98bf-61eeb7bc671b.png)

**Comment by Weisl** [comment]
@LLKoder what do you mean with "special collection" and "special object". I am not sure what you mean? Renaming only selected is not supported for collections if that's the question but it is supported for objects.

**Comment by LLKoder** [comment]
Yes, I mean selected collections. Ok, I see this is not bug it's a new feature.
Will it be supported in future?

**Comment by Weisl** [comment]
I honestly don't know. I don't have any road map for the addon.

**Comment by Weisl** [comment]
You can now rename only selected Collections! Unfortunately, it doesn't work from the 3D View. You have to open the popup renaming panel (Ctrl + F2) from the outliner for it to work. It's in version 1.6.0
