### ISSUE TITLE
[Bug] Numerate

### ISSUE THREAD

**Issue by LLKoder** [Weisl/simple_renaming_panel#101]
The first number the add-on use is two (2) instead one (1).

![image](https://user-images.githubusercontent.com/50442676/145702889-5ee3c221-cefc-4dbd-bfa1-aa92f2cc9c26.png)

Addition: I suggest does not point separate sign ("\_") there. I think It wold be nice if user decides for himself what sign use instead "\_". And not waste time to rename again.

**Comment by Weisl** [comment]
@LLKoder, thanks for reporting. This issue appeared after I made an optimization on the way the numerate operates. It is much faster now than it used to be. I hope I will find some time ofter the holidays to look into it.

**Comment by Weisl** [comment]
@LLKoder As a temporary fix you can use the older version.  
https://github.com/Weisl/simple_renaming_panel/releases/tag/v1.5.1
