### ISSUE TITLE
Addon Updater implementation is not working correctly

### ISSUE THREAD

**Issue by stom66** [Weisl/simple_renaming_panel#102]
Currently the updater for the addon does not work correctly in Blender 3.0.1.

It detects the latest plugin version as the alpha release for Blender 2.8.

Choosing the option to "Install latest master / old version" triggers an error message.

**Comment by Weisl** [comment]
The auto-updater causes many issues. I am thinking of deleting it entirely.

**Comment by Weisl** [comment]
I have updated it to the latest version
