### ISSUE TITLE
Add the ability to slice

### ISSUE THREAD

**Issue by Oxicid** [Weisl/simple_renaming_panel#108]
It would be nice to adapt this script for your addon

import bpy
new_name = input("Enter a new name")
string_cuts = input("Enter the number of characters you want to cut")

first_simbols_cut = True
 
for obj in bpy.context.selected_objects:
    if first_simbols_cut:
        obj.name = f'{new_name}{obj.name[int(string_cuts):]}'
    else:
        obj.name = f'{obj.name[:-int(string_cuts)]}{new_name}'

**Comment by Weisl** [comment]
Can you use search an replace and keep the replace string empty to achieve your goal?

**Comment by Weisl** [comment]
![image](https://user-images.githubusercontent.com/6353016/190651864-d4a2db63-9e20-4615-9cad-363a49887e14.png)
There is also a trim operation
