### ISSUE TITLE
Key bindings resetting to default after restart of blender

### ISSUE THREAD

**Issue by jcdied4me** [Weisl/simple_renaming_panel#130]
I set new key bindings in the addon but they keys reset to default every time I reopen blender.

**Comment by Weisl** [comment]
https://user-images.githubusercontent.com/6353016/206864545-4b736357-d7b4-4cd0-91e1-aa1fbb5a7202.mp4

Bug can be reproduced. Key changes are not stored with the preferences and get reset on every reopening of the addon.

**Comment by Weisl** [comment]
I can confirm the same issue for my other addons: as well:
- Collider tools 
- Cam-Manager

**Comment by Weisl** [comment]
Fix video

Uploading bug130_fast.mp4…

**Comment by Weisl** [comment]
Created a BlenderArtists post with the hope to get some help.
https://blenderartists.org/t/addon-keymap-changes-are-lost-after-restarting-blender/1426451
