### ISSUE TITLE
Suggestion: Rename the panel to "Rename"

### ISSUE THREAD

**Issue by hced** [Weisl/simple_renaming_panel#135]
Just a friendly suggestion. Thanks for making this add-on by the way!

Given how precious real-estate in the N-Panel is, I think the words `simple` and `panel` (in Simple Renaming Panel) become a bit unnecessary. I suggest naming the panel only `Rename`. Short and to the point.

**Comment by Weisl** [comment]
There is an other addon that has Rename as a panel name. I didn't want to use the same. You can easily change the label from the preferences tough.
