### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by arthurbourquin** [Weisl/simple_renaming_panel#137]
Hello,
Thank you for this awesome addon!
Does all the regex works?
I can't achieve this:
^l(.+)
$1l
It is supposed to find every names beginning by "l", remove it an put another "l" at the end.
the $1 dosent seems to work.

**Comment by Weisl** [comment]
Ok
There is a confusion on how this feature is supposed to work. You can only use regex to search for a pattern not You can't use it in the replace field. 
^l(.+) finds the part of the string starting with l
you can then replace it with "asdf"
and lol will become asdfol

**Comment by arthurbourquin** [comment]
Ok, thanks for replying!

Best regards
Arthur
