### ISSUE TITLE
Numerate Start - bug if number is higher than 1

### ISSUE THREAD

**Issue by tonygr1** [Weisl/simple_renaming_panel#138]
Hi, I would very much like to use Numerate Start to a number higher than 1 (with increment of 1). Let's say I set that to 50, then I select 10 objects to rename. What should happen is something like 50,51,52,...,59. What happens instead is 50,100,101,...  The problem is the 2nd object gets 2x the start value (ie, 50x2=100).

This is a really big problem for my use case. I have 10s of 1000s of objects I need to rename, but then numbering does not always start from 1. Please advise if this can be fixed in your next release.

Thank you, Tony

**Comment by Weisl** [comment]
Bug confirmed

start: 50
step: 1
![image](https://github.com/Weisl/simple_renaming_panel/assets/6353016/528c549d-469d-4333-b100-1b6ca4d029a9)

start: 1
step: 50 
![image](https://github.com/Weisl/simple_renaming_panel/assets/6353016/a7155529-6051-4b64-a284-9290d15b0a70)

**Comment by Weisl** [comment]
Found the issue for the 1st part. Shouldn't be too hard to fix

```
    while newName in typelist and newName != active_entity_name:
        newName = basename + separator + (
            '{num:{fill}{width}}'.format(num=(i * step) + startNum, fill='0', width=digits))
        i += 1
```

**Comment by Weisl** [comment]
Uploading bug_138_fix.mp4…

**Comment by Weisl** [comment]
[simple_renaming_panel_fix_138.zip](https://github.com/Weisl/simple_renaming_panel/files/11642482/simple_renaming_panel_fix_138.zip)

@tonygr1 Try this update. It should fix this issue. I have to do something else now. Let me know if there are still issues with that particular issue.

**Comment by tonygr1** [comment]
Wow, thank you so much. This definitely fixed the issue for me!

Best Regards,
Tony Grzesik

**Comment by Weisl** [comment]
Fixed
