### ISSUE TITLE
Addon version #

### ISSUE THREAD

**Issue by tonygr1** [Weisl/simple_renaming_panel#139]
Hi,

Just want you to be aware that when I download and install v1.6.2, then Preferences> Addons, I open the settings for Simple Renaming Panel. It shows Version 1.6.0, even though I installed the ZIP file download with v1.6.2.

**Comment by Weisl** [comment]
I simply missed changing the number. Should be an esay fix for the next version.

**Comment by Weisl** [comment]
Fixed
