### ISSUE TITLE
Naming and Numerate option add to Properly Panel

### ISSUE THREAD

**Issue by tonygr1** [Weisl/simple_renaming_panel#140]
If I want to change Numerate Start/Step, I have to open Preferences> Addons> Simple Renaming Panel. Same thing with naming, such as changing the Separator and Digits. It would be very time-saving to have this added to the Properties Plan. I have a use case where I need to rename 1000s of objects, and need to frequently change the above settings. This is a feature request.

Thank you, Tony

**Comment by Weisl** [comment]
The mentioned properties are currently saved globaly. Meaning that the settings will persist when opening a new Blender file. I could expose those global settings to the properties panel. From a UX perspective this is inconsistent as you can usually only set global settings in the preferences. 
Alternatively I could introduce a new setting, that takes the preference setting as a default but can then be changed in the scene without affecting all new blender files. 
I think that would be the ideal solution and solve your problem while keeping UX consistant.

**Comment by Weisl** [comment]
@tonygr1 
A temporary hack could be to open the preferences in the view: 

![prefsInView](https://github.com/Weisl/simple_renaming_panel/assets/6353016/1dfaa9df-6fb3-4385-8008-5389e2e1ea47)

**Comment by Weisl** [comment]
![2023-12-13 10_56_12-_ (Unsaved) - Blender 4 0](https://github.com/Weisl/simple_renaming_panel/assets/6353016/f559ceea-29c4-4c16-b75c-ca42861d66ce)

I added a button to get quickly to the preferences. This should make it less cumbersome
