### ISSUE TITLE
Numerate by Axis Order

### ISSUE THREAD

**Issue by tonygr1** [Weisl/simple_renaming_panel#141]
Hi,

I have a feature request, and I'm willing to pay for the work if you are open to working on this. I have Blender projects (currently using v3.5.1) that can have 65,000 objects or more that need to be renamed. For my use case, the Numerate order/sequence is critically important. Using Simple Renaming Panel, I can accomplish the desired Numerate sequence order only if I individually select each object.

- If I select objects one at a time, each object individually, then the Numerate will respect my selection order and will number the objects accordingly (e.g., .001, .002, .003, etc.).
- However, if I do a box-select of a column or row of objects containing 100 objects, the numerate numbering order will be random.

My feature request is to have an option in the Properties Panel to numerate according to the following options:

- Numerate according to either X, Y, or Z axis.
- Numerate according to Location value. Options would be from smallest-to-largest, or largest-to-smallest.

Blender has information knowing where the object origins are located in 3D space. So for example, if I had 100 cubes lined up on the X-axis, I may want the numbering sequence to run from left-to-right, for example. Even if the Z-axis values are not the same, it can still number from smallest-X-location-value to largest-X-location value, for example. If 2 or more X-location values are identical (say multiple cubes in Z-axis), then in this case, use the smaller Z-axis value first, then the next larger Z-axis value, and so forth.

If you may be open to working on this, please let me know, and I'll send you my email address, because I would like to contribute money for the effort required.

Thank you,
Tony

**Comment by Weisl** [comment]
I need to check the code, I am not sure how feasible this request is.

**Comment by DragonMapMaker** [comment]
"Numerate according to either X, Y, or Z axis" would be amazing for me as well. Thanks for a great addon by the way!

**Comment by Weisl** [comment]
This looks useful to implement it:
https://blender.stackexchange.com/questions/72691/sort-a-list-of-objects-by-their-distance-from-a-point

**Comment by Weisl** [comment]
Basic functionality is implemented. Just need to do some UI improvements

**Comment by Weisl** [comment]
@DragonMapMaker  and @tonygr1. Sorting by Axis is now supported in Version 2.0
