### ISSUE TITLE
Renaming by selection order does not work.

### ISSUE THREAD

**Issue by B0ilz** [Weisl/simple_renaming_panel#142]
Hi, I know that renaming order is currently based on the order the object data is stored, but in issue #70 you state that selection order now works for renaming.  This doesn't seem to work from what I have tried.  Specifically my issue is when I take a bone, subdivide it X amount of times and try to rename it after selecting in the order that I want.  Simple rename seems to still rename it according to the object data, as blender (for some reason) likes to reverse the numeration of the new subdivided bones except the first one.

**Comment by Weisl** [comment]
Hi, 
Selection order is only supported for objects, not for bones! To achieve this, I am manually storing the selected object one by one in a list upon selection. Blender does not offer access to the selection order through it's API. I will probably look into expanding the functionality in the future but there are no plans atm.

**Comment by B0ilz** [comment]
Thanks, I hope maybe the main Blender devs will look at the subdivide bone function and change the order if it's possible.

**Comment by Weisl** [comment]
Closing as there is already a ticket for bone order and it is mostly limited by Blender API
