### ISSUE TITLE
Numeration of Mesh Data not working

### ISSUE THREAD

**Issue by DianaBerg** [Weisl/simple_renaming_panel#143]
Issue: When using the Simple Renaming Panel with the target Data on multiple selected objects, numeration stops at _000 and then adds .001 to the mesh data of the remaining objects.

Ideal behavior: Renaming the mesh data of multiple selected objects with the "Numerate" option on, would numerate each unique data following the numeration settings (_000, _001, _002 for example).

A workaround exists: Disable Numerate and add a "_@n" variable to the end of the name.

Thank you for taking the time to read this. Your tool has saved me a lot of time and effort and any improvements would be icing on the cake.

**Comment by Weisl** [comment]
Bug confirmed

**Comment by Weisl** [comment]
Fixed for the next release
