### ISSUE TITLE
Rename by selection keeps some objects selected after deselection.

### ISSUE THREAD

**Issue by DragonMapMaker** [Weisl/simple_renaming_panel#144]
Hi,
Thanks for a great add-on, it's super useful!

(This happens when selecting items in the 3d view and using Replace Names with Numerate turned on.)
I noticed in the last update where you added renaming by selection order (which is amazing) that occasionally I'll have objects that I've previously renamed get renamed along with the new selection. I can't replicate this easily so not sure quite what's going on but I keep noticing that Objects that were not selected (but were previously renamed) have been renamed along with the currently selected objects. 
It's also never the whole previous selection but just a couple of objects from the previous selection. 

(I can't 100% tell what version I am on, Gumroad version says 1.6.2 but when I install that it says it is still version 1.6.0 and says I need to update and restart Blender but it always stays at v1.6.0)

Thanks again.

**Comment by Weisl** [comment]
This is weird and I could not reproduce it. I might add an additional security check tough!

**Comment by Foulvertex** [comment]
Can confirm the issue. Version 1.6.2. Idk what exactly triggers the bug but after it happens once it is always the same: it only happens if you "Rplace Names" with "Only Selected" and "Numerate" both both enabled. I'll try reproduce this bug more thouroughly on a clean install.

**Comment by Foulvertex** [comment]
It seems the problem is with "Use Selection Order" option. Without it works like a charm.

P.S.  Thanks for a wonderfull addon, absolute lifesaver!

**Comment by Weisl** [comment]
This issue is connected to the custom selection sorting I am doing to allow for selection order to work. I need to dig deeper into the code to understand why this is happening. This is rather complex for my limited coding skills.

**Comment by Weisl** [comment]
I might have fixed this one but needs more testing
