### ISSUE TITLE
Blender crashes when running Add Surface in Bsurfaces

### ISSUE THREAD

**Issue by nkarin2160** [Weisl/simple_renaming_panel#145]
This crash was observed using Blender 4.0.1. Not verified elsewhere.
Below are the steps to reproduce the crash
1.Enable simple_renaming_panel and Bsurface in Addon settings
2. Add cube and UV sphere
(Bsurface settings start here)
3.Assign cube to mesh of BSurface
4.Click initlize (Add Bsurface mesh)
5. Add two annotation lines to the UV sphere
6.Blender crashes when clicking Add Surface

**Comment by nkarin2160** [comment]
Yes, I don't know the cause, but I checked them one by one and the crash occurs in Bsurface only when simple_renaming_panel is enabled. When this is disabled, the Bsurface is working without problems

**Comment by Weisl** [comment]
I can only imagine that this is connected to the code for renaming objects in selected order. I will try that out and make it optional potentially.
Thanks for reporting

**Comment by nkarin2160** [comment]
Thanks for checking it out. This is a great add-on and useful!

**Comment by Weisl** [comment]
It is not connected to the selection order. I don´t get any logs or errors when it crashes. I am not sure on how to further investigate this.

**Comment by Weisl** [comment]
Not sure how to approach this bug
