### ISSUE TITLE
Renaming data as object name + empty string

### ISSUE THREAD

**Issue by qforce85** [Weisl/simple_renaming_panel#30]
Just found this nifty addon, great job!

One issue I ran into: On the Data tab, I can't seem to be able to rename data entities so that they get the same name as their object. In other words, the field "Data = Objectname + :" is left empty. When I try to do that, the tool says "No Objects Renamed".

I also think there's a typo in there: It should be "Object Name", not "Objectname".

Cheers

**Comment by Weisl** [comment]
Thank you for posting this issues. I am going to have a look at it :)

**Comment by Weisl** [comment]
Should be fixed by now. Sorry that it took me so long.

**Comment by qforce85** [comment]
Ah, wasn't a big deal. Glad I could help!
