### ISSUE TITLE
Renaming Bones .L to _L does not quite work for all bones

### ISSUE THREAD

**Issue by enzyme69** [Weisl/simple_renaming_panel#31]
I thought it would be pretty simple, I need to find all Bones with suffix ".L" and replace it with "_L" but somewhat you add on does not find all the bones, even if I select the bone.

Any tippers? Thanks!

**Comment by Weisl** [comment]
Thank for your report. I'm gonna have a look at it this evening.

**Comment by Weisl** [comment]
Sorry that it took me so long. The issue should be fixed by now. It has been pushed to the master. If you run into new issues let me know.
