### ISSUE TITLE
Proposal for behavior (especially in rigging process)

### ISSUE THREAD

**Issue by DiegoSG** [Weisl/simple_renaming_panel#35]
Hi, I realy like the addon, I have two proposal

- The first one is to keep the mode (edit, pose, etc) after renaming, because if you are switching in objet mode an pose mode all the time, the workflow become a bit slow, especialy in rigging process. I think if yo make a variable before with the process with the mode avaible, you can mantain the mode after renaming... but you know more than me XD

- And the second one is have the posibiliti to turn off the popup message after renaming, they are a bit annoying when you have to renamin diferent selections.

 Again, it is a good addon, thanks a lot
Sorry for my poor english XD

**Comment by Weisl** [comment]
Hi, 
thanks for your feedback. I have fixed both issues. You can simply donwload the newest version from the github master branch.  Other new things I have just added are the support for regex expressions and actions. If you find any issues, please contact me :). 

1. There was a bug, so I disabled it temporarily. Now it should work
2. I have added a setting in the user preferences switch of the popup

You would do me a great favor if you could rate my addon on gumroad :)! https://gumroad.com/l/simple_renaming_panel
