### ISSUE TITLE
Cool addon! Thank you!

### ISSUE THREAD

**Issue by brothermechanic** [Weisl/simple_renaming_panel#36]
Can i add an idea to you?
This is krename program
![Screenshot_20190419_103350](https://user-images.githubusercontent.com/3109995/56413008-b1d64b00-628e-11e9-9f0f-13ffcb18b3d1.png)
It has super cool feature - Insert Part off Name
Do you plan to add something in your addon?
I know it has Trim finction, but ot don't exactly so
Thank you

**Comment by Weisl** [comment]
Hi,
this feature is currently not planed. I am focusing on UI/UX right now and have some other features i want to implement. I will consider this proposal when I finished the current features 😁. Thanks for your feedback.

**Comment by Weisl** [comment]
Check put the new update and tell me if it fits your needs.
