### ISSUE TITLE
unable to activate addon 

### ISSUE THREAD

**Issue by jirzin** [Weisl/simple_renaming_panel#40]
blender 2.8 version: 2019-02-02 00:58 hash: 4ef09cf937f2
simple renaming panel version 1.3.1 

after addon was installed from zip master file I was unable ti activate addon in addons window
checkbox seems unresposible

**Comment by Weisl** [comment]
Hi, I had a bug in the master branch. Let me know if the issue still exists.

**Comment by jirzin** [comment]
it works now... thx
