### ISSUE TITLE
Not working in Blender 2.81?

### ISSUE THREAD

**Issue by Sinister366** [Weisl/simple_renaming_panel#42]
Hello, I'm trying to use this addon as part of the rigging course (from p2 design).

When I try to rename my bones with the search and replace feature, I get an error (which he does in the video also) but then my bones aren't renamed.  If I go back to Blender 2.8, I'm able to get it to work but then when I import that scene back into 2.81, my bones are no longer renamed.
Do you know if this is working reliably (or should be) in 2.81 yet?

EDIT:  Ok if I hit the button a second time afterwards, now my bones are renamed.   Even so maybe something to check out.

**Comment by Weisl** [comment]
I have rewritten some parts of the code. There seems to be a bug when renaming bones in object mode but otherwise it should work
