### ISSUE TITLE
"Only Selected" Checkbox Brings An Error

### ISSUE THREAD

**Issue by lukeyurkovich** [Weisl/simple_renaming_panel#48]
![Screenshot (3)](https://user-images.githubusercontent.com/58205804/69606264-6dd0d300-1033-11ea-9dad-2ef5edfa8316.png)

I get this error message whenever I try to batch rename my selected bones. If I don't check the "only selected" box then it works, but I don't want to rename everything.

**Comment by Weisl** [comment]
I will check i out. Try to go to edit or ideally pose mode. It should work then. I didn't test it in object mode as i wasn't thinking about that. I think i know whats the issue

**Comment by Weisl** [comment]
Can't fix this issue quickly but I will at least handle the error. Fix works for now but I will test it tomorrow before pushing it to master.

![image](https://user-images.githubusercontent.com/6353016/69676812-394c2e00-10aa-11ea-885c-f95dcf639b03.png)

If you want, you can download the fixed version from this branch.
