### ISSUE TITLE
"Only Selected" issue with similar named bones

### ISSUE THREAD

**Issue by Jonathan3802857237** [Weisl/simple_renaming_panel#61]
With multiple Armatures that have shared bone-names you cant rename only the bones from the currently selected armature without also renaming the bones from all other armatures.

For Example:
Here I made 2 armatures with the same bone names.
![-10](https://user-images.githubusercontent.com/16743363/84893039-e6b27d80-b09e-11ea-9c5e-096e3c26983c.jpg)

When I'm renaming only selceted from "Armature A" it renames also all from "Armature B"
![-20](https://user-images.githubusercontent.com/16743363/84893220-2aa58280-b09f-11ea-892b-69ecf96b8b20.jpg)

**Comment by Weisl** [comment]
![fix_rename_only_selected_bones](https://user-images.githubusercontent.com/6353016/85920944-e9705800-b880-11ea-90e8-ebd0809c9ebf.gif)

I just made a partial fix for it. It will only rename the bones of selected OBJECTS. This means if you select only the second armature before entering Pose/Edit mode. It will only rename the bones in that armature. 
If you select both Armatures and enter Pose mode after, it will rename the bones for both. It is not ideal from a UX perspective as it's hard to understand what are the rules  "behind" it.

Let me know if that solves your issues. 

Thanks for reporting the bug in a really clear and well illustrated way!

**Comment by Weisl** [comment]
It's in master. You should be able to test it when updating the addon.
