### ISSUE TITLE
Suggestion: Rename  only selected Collection

### ISSUE THREAD

**Issue by bluesleex** [Weisl/simple_renaming_panel#69]
this addon is awesome, only A little regret,there is no option of "only selected Collection", Very Hopefully to add this feature in the future version.
--

**Comment by Weisl** [comment]
Unfortunatly, this feature is not so easy to implement. How would you select the collections? I can't really acces the selection from the outliner as it has another context than the 3D view. The addon can only access the 3D view context. I could porbably get around this issue, but what if there are two outliners open? Which one to take?

I was thinking of having a list in the addon, where you could select different data, collections, images etc. to perform operations on them. This is a bigger implementation and I don't plan to tackle it in the next time, as I am focusing on other projects. 

Thank you for reaching out! Feadback is alway appreciated and I might find the time at some point in the further future :)

**Comment by Weisl** [comment]
Added for v1.6.0
