### ISSUE TITLE
Suggestion: Renaming for UV maps?

### ISSUE THREAD

**Issue by s-ilent** [Weisl/simple_renaming_panel#71]
Hi! Thanks so much for your hard work on this project.

It would be nice to have the ability to batch rename UV maps on meshes. This seems like something not covered by anything except writing a bespoke script, so it would be useful to have this as functionality in the plugin.

**Comment by Weisl** [comment]
I agree. Can you probably explain to me how you would use it and what you need it for? I made small scripts in the past to rename all of the first UV maps to "main" and the second to "lightmap". These functionalities are great but they don't fit well into the current design of the addon. Having proper real-life use cases helps me to see if it fits into the addon and in general making the tool better.

**Comment by Weisl** [comment]
This feature has been implemented as part of #112
