### ISSUE TITLE
installation keymap error

### ISSUE THREAD

**Issue by lalamax3d** [Weisl/simple_renaming_panel#72]
Hi, blender 2.83 version installed correctly but preferences keymap area shows error.
Console log is like >>
```
File "/home/user/.config/blender/2.83/scripts/addons/simple_renaming_panel/renaming_preferences.py", line 325, in draw
    km = kc.keymaps['3D View Generic']
KeyError: 'bpy_prop_collection[key]: key "3D View Generic" not found'
```

any ideas.??

**Comment by Weisl** [comment]
Issue has been fixed on the develop branch. 
https://github.com/Weisl/simple_renaming_panel/tree/Develop
