### ISSUE TITLE
All bones of same name across all armatures renamed, not just selected armature.

### ISSUE THREAD

**Issue by Mrfunreal** [Weisl/simple_renaming_panel#73]
Heya.

In my blender files i pretty much always have viewmodels and worldmodels for a game, which share the same arm bone names. When I flip my viewmodel bones and then rename all bones from "..._R_..." to "..._L_..." all bones of all existing armatures will be renamed. Which ends up with my worldmodel bones having all "_R_" bones being renamed to "_L_...001".
Doesn't matter if i pick "only selected".

Would be nice if you could change "selected only" to work as one would think it should work.

**Comment by Weisl** [comment]
Hey @Mrfunreal
I am working on a fix for that. Since I am not a rigger myself. It is hard for me to understand all the details. Renaming the bones is much more difficult than one might expect. I am working on a fix for this and hope to get it to master today :)

**Comment by Weisl** [comment]
I made some improvements in this branch. You can download it. If you only select one armature and rename the selected bones there it will work. If you have multiple armatures in edit mode, it will still rename the bones for all of them, even if only selected is active. 
![4AHHhxod8T](https://user-images.githubusercontent.com/6353016/132985981-19cb5e63-78c6-4b69-ab8a-1cd14a7319c4.gif)

https://github.com/Weisl/simple_renaming_panel/tree/Develop

**Comment by Weisl** [comment]
This issue does not appear after the change for #85 anymore.
