### ISSUE TITLE
Context is incorrect error

### ISSUE THREAD

**Issue by do-kevin** [Weisl/simple_renaming_panel#74]
Hey there, I'm running Blender 2.93 and simple renaming panel 1.5.0. This error pops up when I press Search and Select. When I press Search and Replace, it says no objects are found.
[
![Untitled](https://user-images.githubusercontent.com/40156784/131241699-97d101fb-ff24-4608-b3c4-a9cddb56d0ff.png)
](url)

**Comment by do-kevin** [comment]
Oh my mistake, I chose the wrong target and did not tick `Only Selected`

**Comment by Weisl** [comment]
Hi do-kevin, 
Thanks for reaching out and reporting this issue. I am glad that it worked with only selected. The error shouldn't appear otherwise as well. I will take a quick look. Probably I can get rid of it or at least make a useful error message.

**Comment by Weisl** [comment]
Fix has been submitted to the develop branch. Feel free to test it out and let me know if the issue still arrises. I included some improvements for renaming bones. If you select "Bones" in the target dropdown. You can "search and select" as well as "search and replace" in edit mode now. 
https://github.com/Weisl/simple_renaming_panel/tree/Develop

**Comment by do-kevin** [comment]
> Fix has been submitted to the develop branch. Feel free to test it out and let me know if the issue still arrises. I included some improvements for renaming bones. If you select "Bones" in the target dropdown. You can "search and select" as well as "search and replace" in edit mode now. https://github.com/Weisl/simple_renaming_panel/tree/Develop

Sorry for the very late reply. The issue appears to be gone and the appropriate tooltip shows up. Thanks!
