### ISSUE TITLE
Suggestion: Rename if the selection has specific property 

### ISSUE THREAD

**Issue by ALIEN31ITA** [Weisl/simple_renaming_panel#75]
For example: Multiple materials with different names that use the same texture file, and it would affect those,
or any other property.

Both Texture and Nodes... if possible.
![image](https://user-images.githubusercontent.com/35733884/132427097-66d968e9-70a6-4a22-aee3-66b83ca37402.png)

**Comment by Weisl** [comment]
@ALIEN31ITA Thanks for the request. This sounds like a cool feature but it would require major effort to implement and create a useful UI. I don't expect this feature to be implemented in the future. Sorry for that.
