### ISSUE TITLE
Numerate on bones not working

### ISSUE THREAD

**Issue by jaldoyle** [Weisl/simple_renaming_panel#85]
Numerate on bones not working, names first bone correctly but the rest selected the same as the first bone and blender adds its default numeration. using v1.5.1 in blender v2.93.3.

![image](https://user-images.githubusercontent.com/69980837/133758936-e9d227ff-c0d7-46a3-83bb-1ac3aee06c71.png)

**Comment by Weisl** [comment]
Thanks for reporting. I will take a look at it on Sunday

**Comment by Weisl** [comment]
It seems that the issue appears when renaming bones in Bone Edit mode but not in Bone Pose mode. @jaldoyle You could try renaming the bones in Pose mode for now, at least until I submit a fix. I am investigating it further and found another issue connected to renaming selected bones.

**Comment by Weisl** [comment]
I think I fixed it with the last submit. I need to test it in the next few days and push it to master.

**Comment by Weisl** [comment]
It's in develop
