### ISSUE TITLE
Numbering non order

### ISSUE THREAD

**Issue by Paladinqp** [Weisl/simple_renaming_panel#98]
Hello. How create numbering which starts with 01. Yes, we can replace "_0" on "_". But why dont work original Replace Names(.

![11111](https://user-images.githubusercontent.com/93562249/140440721-3cfa22a0-f834-4838-a332-ef3b128eb254.jpg)

**Comment by Weisl** [comment]
Hello,
That's interesting, it is supposed to worke the way you expected it to be. I will need to take a look at it. 
Thanks for reaching out to me 🙂

**Comment by Weisl** [comment]
It is a reproducable bug. I need to investigate this when I have the time.

**Comment by Weisl** [comment]
#101 This should be fixed with this
